"""
Generates installer_gpu_pack.nsi -> GrainAnalyzer_GPU_Pack.exe (decision D-32).

The pack is an OPTIONAL second installer that overlays the NVIDIA CUDA build
of torch onto an existing Grain Analyzer installation. It is fully offline:
all files come from <pack_dir> (built by make_gpu_pack.py) at build time.
It refuses to run unless the same version of the base app is installed and
the app is closed.

    python create_gpu_pack_nsis.py [pack_dir]
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from version import __version__, APP_NAME as _APP_NAME

NSIS_TEMPLATE = r"""
; Grain Analyzer GPU Pack - generated by create_gpu_pack_nsis.py
!define APP_NAME "__APP_NAME__"
!define APP_VERSION "__APP_VERSION__"
!define APP_EXE "GrainAnalyzer.exe"
!define INSTALL_REG_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\GrainAnalyzer"

Name "${APP_NAME} ${APP_VERSION} - GPU Pack"
OutFile "GrainAnalyzer_GPU_Pack.exe"
RequestExecutionLevel admin
; ~3.5 GB of CUDA libraries: solid LZMA keeps the installer under the 2 GB
; NSIS / GitHub Release limit (CI fails the build if it does not).
SetCompressor /SOLID lzma
SetCompressorDictSize 64

!include "MUI2.nsh"
!define MUI_ABORTWARNING
!define MUI_ICON "resources\icon.ico"
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_LANGUAGE "English"

Function .onInit
  ; Same registry view as the base installer (it does not call SetRegView).
  ReadRegStr $INSTDIR HKLM "${INSTALL_REG_KEY}" "InstallLocation"
  ReadRegStr $1 HKLM "${INSTALL_REG_KEY}" "DisplayVersion"
  StrCmp $INSTDIR "" notinstalled
  IfFileExists "$INSTDIR\${APP_EXE}" 0 notinstalled
  StrCmp $1 "${APP_VERSION}" versionok
  MessageBox MB_OK|MB_ICONSTOP "This GPU pack is for version ${APP_VERSION}, but version $1 is installed. Use the matching pack, or reinstall ${APP_NAME}." /SD IDOK
  Abort
notinstalled:
  MessageBox MB_OK|MB_ICONSTOP "${APP_NAME} ${APP_VERSION} is not installed. Run GrainAnalyzer_Setup.exe first, then this GPU pack." /SD IDOK
  Abort
versionok:
  ; A running app keeps its exe and torch DLLs locked; a half-overlaid
  ; install would be broken. Windows refuses write access to a running exe.
  ClearErrors
  FileOpen $2 "$INSTDIR\${APP_EXE}" a
  IfErrors appisrunning
  FileClose $2
  Goto done
appisrunning:
  MessageBox MB_OK|MB_ICONSTOP "Close SEM Grain Analyzer, then run this again." /SD IDOK
  Abort
done:
FunctionEnd

Section "GPU Pack"
  SetOutPath "$INSTDIR"
  SetOverwrite on
  ; CPU-only files that must not remain next to the CUDA build
__REMOVE_LINES__
  File /r "__PACK_DIR__\*.*"
  WriteRegStr HKLM "${INSTALL_REG_KEY}" "GpuPack" "${APP_VERSION}"
SectionEnd
"""


def _nsis_escape(s):
    return s.replace("$", "$$").replace('"', "$\\\"")


def remove_lines(removed_rel_paths):
    """NSIS Delete lines for files, then RMDir (non-recursive, deepest first)."""
    files = [p.strip().replace("/", "\\") for p in removed_rel_paths if p.strip()]
    dirs = set()
    for p in files:
        parts = p.split("\\")[:-1]
        for i in range(1, len(parts) + 1):
            dirs.add("\\".join(parts[:i]))
    out = [f'  Delete "$INSTDIR\\{_nsis_escape(p)}"' for p in files]
    out += [f'  RMDir "$INSTDIR\\{_nsis_escape(d)}"'
            for d in sorted(dirs, key=lambda d: (-d.count("\\"), d))]
    return "\n".join(out)


def generate(pack_dir="dist_gpu_pack", removed_paths=()):
    return (NSIS_TEMPLATE
            .replace("__APP_NAME__", _APP_NAME)
            .replace("__APP_VERSION__", __version__)
            .replace("__REMOVE_LINES__", remove_lines(removed_paths))
            .replace("__PACK_DIR__", pack_dir))


def main(argv):
    pack_dir = argv[1] if len(argv) > 1 else "dist_gpu_pack"
    from make_gpu_pack import removed_list_path
    removed = []
    rp = removed_list_path(pack_dir)
    if os.path.isfile(rp):
        with open(rp, encoding="utf-8") as f:
            removed = f.read().splitlines()
    with open("installer_gpu_pack.nsi", "w") as f:
        f.write(generate(pack_dir, removed))
    print(f"installer_gpu_pack.nsi created ({len(removed)} CPU-only files to delete).")


if __name__ == "__main__":
    main(sys.argv)
