"""
User-visible text is American English (user request after the batch 4
tutorial review: "analysing" reads as a typo).  String literals -- not
docstrings or comments -- in ui/ and the user-facing messages of
core/ must not use British spellings.  Identifiers, settings keys, palette
keys and parsing tables that saved data depends on are listed in ALLOWED.
"""
from __future__ import annotations

import io
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

BRITISH = re.compile(
    r"(?<![A-Za-z_])("
    r"analys(e|ed|ing)|re-?analys(e|ed|ing)|analyser|colour(s|ed|ing)?|centre[ds]?"
    r"|centring|behaviour|grey(ed|s)?|licence[s]?"
    r"|cancelled|cancelling|labelled|labelling|modelled|(micro|milli|nano)?metres?"
    r"|catalogue|favourite|programme|recognis(e|ed)|organis(e|ed)|summaris(e|ed)"
    r"|customis(e|ed)|normalis(e|ed)|optimis(e|ed)|finalis(e|ed)|artefacts?"
    r")(?![A-Za-z_])", re.IGNORECASE)

#: string literals that are data, not text shown to the user
ALLOWED = {
    ("ui/pages/lot_results.py", "grey"),         # status-level key
    ("ui/pages/report_widgets.py", "grey"),      # palette key
    ("ui/gallery.py", "labelled"),               # QSS property name
    ("core/metrics.py", "grey"),                 # status-level value
    ("core/sem_metadata.py", "micrometre"),      # metadata unit parsing
}


def string_literals(path: Path):
    """(line, text) of every string literal that is not a docstring."""
    src = path.read_text(encoding="utf-8")
    toks = [t for t in tokenize.generate_tokens(io.StringIO(src).readline)
            if t.type not in (tokenize.NL, tokenize.COMMENT)]
    for i, t in enumerate(toks):
        if t.type != tokenize.STRING:
            continue
        prev = toks[i - 1] if i else None
        nxt = toks[i + 1] if i + 1 < len(toks) else None
        if (prev is None or prev.type in (tokenize.INDENT, tokenize.DEDENT, tokenize.NEWLINE)) \
                and (nxt is None or nxt.type in (tokenize.NEWLINE, tokenize.ENDMARKER)):
            continue                                    # docstring
        if "generated by ui/design/theme.py" in t.string:
            continue                                    # the QSS template (property names)
        yield t.start[0], t.string


def _offenders(dirs):
    out = []
    for d in dirs:
        for p in sorted((ROOT / d).rglob("*.py")):
            rel = p.relative_to(ROOT).as_posix()
            for line, text in string_literals(p):
                for m in BRITISH.finditer(text):
                    if (rel, m.group(0).lower()) in ALLOWED:
                        continue
                    out.append(f"{rel}:{line}: {m.group(0)}")
    return out


def test_ui_text_is_american_english():
    # reports/ (export text) gets its own pass with the report restructure
    assert _offenders(("ui",)) == []


def test_core_user_messages_are_american_english():
    assert _offenders(("core", "data")) == []


def test_the_guard_catches_british_spellings():
    for w in ("Analysing 3 images", "Not analysed", "Re-analyse", "colour", "centred",
              "Third-party licences", "cancelled", "greyed out", "micrometres"):
        assert BRITISH.search(w), w
    for w in ("Analyzing 3 images", "Analysis", "analyses of 3 lots", "color", "colors",
              "centered", "license", "canceled", "grayed", "micrometers", "analyzed"):
        assert not BRITISH.search(w), w
